let btn1=document.querySelector('#doublebtn')
btn1.addEventListener('dblclick',()=>{alert("Hello")})
let btn2=document.querySelector('#enterbtn')
btn2.addEventListener('mouseenter',()=>{alert("Hello")})
let btn3=document.querySelector('#leavebtn')
btn3.addEventListener('mouseleave',()=>{alert("Hello")})
let btn = document.querySelector('#btn')
btn.addEventListener('click',()=>{alert("Hello ")})